// js song file for autocomplete
songs = ["Alabama",
         "Alice D. Millionaire",
         "All Around This World",
         "All I Have To Do Is Dream",
         "All I Really Want To Do",
         "All Over Now",
         "Alligator",
         "Althea",
         "And We Bid You Goodnight Jam",
         "Are You Lonely For Me Baby?",
         "Around",
         "Attics",
         "B.E. Women",
         "BIODTL",
         "BT Wind",
         "Baba O'Riley",
         "Babe It Ain't No Lie",
         "Baby Blue",
         "Baby What You Want Me To Do",
         "Bad Moon Rising",
         "Ballad Of A Thin Man",
         "Ballad Of Casey Jones",
         "Ballad Of Ira Hayes",
         "Banana Boat Song",
         "Barbara Allen",
         "Bass And Drums",
         "Bass Solo",
         "Beer Barrel Polka",
         "Believe It Or Not",
         "Bertha",
         "Betty And Dupree",
         "Bid You Goodnight",
         "Big Boss Man",
         "Big Boy Pete",
         "Big Railroad Blues",
         "Big River",
         "Bird Song",
         "Black Muddy River",
         "Black Peter",
         "Black Queen",
         "Blackbird",
         "Blow Away",
         "Blue Moon",
         "Blues For Allah",
         "Blues Jam",
         "Blues Stay Away From Me",
         "Bo Diddley",
         "Bob Star",
         "Bobby McGee",
         "Born Cross-Eyed",
         "Born On The Bayou",
         "Bound In Memories",
         "Box Of Rain",
         "Boy In The Bubble",
         "Bring Me My Shotgun",
         "Brokedown Palace",
         "Broken Arrow",
         "Brother Esau",
         "Built To Last",
         "Bye Bye Love",
         "CC Rider",
         "California Earthquake",
         "Candyman",
         "Cardboard Cowboy",
         "Casey Jones",
         "Cassidy",
         "Cathy's Clown",
         "Caution",
         "Caution Jam",
         "Checkin Up On My Baby",
         "Childhood's End",
         "Children Of The Eighties",
         "Chimes Of Freedom",
         "China Cat",
         "China Cat Sunflower Jam",
         "China Doll",
         "Chinatown Shuffle",
         "Chinese Bones",
         "Clementine",
         "Clementine Jam",
         "Cold Jordan",
         "Cold Rain",
         "Come Back Baby",
         "Comes A Time",
         "Corrina",
         "Cosmic Charlie",
         "Cowboy Song",
         "Crazy Fingers",
         "Cream Puff War",
         "Cryptical",
         "Cryptical Envelopment Jam",
         "Cumberland",
         "Dancin",
         "Dark Hollow",
         "Dark Star",
         "Dark Star Jam",
         "Darkness Darkness Jam",
         "Darlin Carey",
         "Day Job",
         "Day Tripper",
         "Days Between",
         "Dead Man, Dead Man",
         "Deal",
         "Death Don't Have",
         "Death Letter Blues",
         "Deep Elem Blues",
         "Desolation Row",
         "Devil With The Blue Dress On",
         "Dire Wolf",
         "Do You Wanna Dance?",
         "Doin' That Rag",
         "Don't Ease",
         "Don't Keep Me Waiting Too Long",
         "Don't Need Love",
         "Don't Think Twice, It's Alright",
         "Down In The Bottom",
         "Down So Long",
         "Drink Up And Go Home",
         "Drums",
         "Dupree's",
         "Early Morning Rain",
         "Easy Answers",
         "Easy To Love You",
         "Easy Wind",
         "Eighteen Children",
         "El Paso",
         "Empty Pages",
         "Estimated",
         "Eternity",
         "Every Time You Go Away",
         "Eyes",
         "FOTD",
         "Far From Me",
         "Feedback",
         "Fever",
         "Fire",
         "Foolish Heart",
         "Forever Young",
         "Foxy Lady Jam",
         "Franklin's",
         "Frozen Logger",
         "Funiculi Funicula",
         "GDTRFB",
         "GDTRFB Jam",
         "Games People Play",
         "Gathering Flowers for the Master's Bouquet",
         "Gentlemen Start Your Engines",
         "Get Back",
         "Gimme Some Lovin'",
         "Gloria",
         "Gonna Change My Way Of Thinking",
         "Good Golly Miss Molly",
         "Good Lovin'",
         "Good Morning Little Schoolgirl",
         "Good Times",
         "Good Times Blues",
         "Goodnight Irene",
         "Gotta Serve Somebody",
         "Greatest Story",
         "Green Green Grass Of Home",
         "Green Onions",
         "Green River",
         "Half-Step",
         "Handsome Cabin Boy Jam",
         "Happiness Is Drumming",
         "Hard To Handle",
         "He Was A Friend Of Mine",
         "He's Gone",
         "Heart Of Me",
         "Heart Of Mine",
         "Heaven Help The Fool",
         "Heaven's Door",
         "Hell In A Bucket",
         "Help",
         "Help Me Rhonda",
         "Here Comes Sunshine",
         "Hey Bo Diddley",
         "Hey Jude",
         "Hey Jude Reprise",
         "Hey Little One",
         "Hey Pocky Way",
         "Hi-Heel Sneakers",
         "Hide Away",
         "High Time",
         "Highway 61 Revisited",
         "Hog For You Baby",
         "How Long Blues",
         "How Sweet It Is",
         "Hully Gully",
         "I Ain't Superstitious",
         "I Fought The Law",
         "I Hear A Voice Callin'",
         "I Second That Emotion",
         "I Want To Tell You",
         "I Want You",
         "I Washed My Hands In Muddy Water",
         "I Will Take You Home",
         "I'll Be Your Baby Tonight",
         "I'm A Man",
         "I'm Free",
         "I'm So Lonesome I Could Cry",
         "I've Just Seen A Face",
         "If Not For You",
         "If The Shoe Fits",
         "Iko Iko",
         "In The Pines",
         "In The Summertime",
         "It Hurts Me Too",
         "It's A Man's World",
         "It's A Sin",
         "It's A Sin Jam",
         "It's All Too Much",
         "J.B. Goode",
         "Jack Straw",
         "Jack-A-Roe",
         "Jam",
         "Joey",
         "John Brown",
         "John Hardy",
         "John's Other",
         "Just A Little Light",
         "Just Want To Make Love",
         "KC Moan",
         "Kansas City",
         "Katie Mae",
         "Keep On Growing",
         "King Bee",
         "L.L. Rain",
         "LSD",
         "La Bamba",
         "Lady Di And I",
         "Last Time",
         "Lazy Lightning",
         "Lazy River Road",
         "Let It Be Me",
         "Let It Grow",
         "Let It Rock",
         "Let Me In",
         "Let Me Sing Your Blues Away",
         "Let The Good Times Roll",
         "Liberty",
         "Lindy",
         "Little Sadie",
         "Logger Song",
         "Long Black Limousine",
         "Long Tall Sally",
         "Loose Lucy",
         "Loser",
         "Lost Sailor",
         "Louie Louie",
         "Love The One You're With",
         "Lovelight",
         "Lovelight Jam",
         "Lucifers Eyes",
         "Mack The Knife",
         "Maggie's Farm",
         "Main Ten",
         "Main Ten Jam",
         "Mama Tried",
         "Man Of Peace",
         "Man Smart",
         "Mason's Children",
         "Matilda",
         "Maybe You Know",
         "Mexicali",
         "Midnight Hour",
         "Might As Well",
         "Mighty Quinn",
         "Mind Left Body Jam",
         "Mind To Give Up Livin'",
         "Mindbender",
         "Minglewood Blues",
         "Miracle",
         "Mission",
         "Mojo",
         "Mona",
         "Money Money",
         "Monkey And The Engineer",
         "Morning Dew",
         "Mountain Jam",
         "Mountains Of The Moon",
         "Mr. Charlie",
         "Mr. Fantasy",
         "Mr. Tambourine Man",
         "Music",
         "My Babe",
         "My Own Fault",
         "Mystery Train",
         "NFA",
         "NFA Jam",
         "Neighbourhood Girls",
         "Never Trust A Woman",
         "New Orleans",
         "New Potato Caboose",
         "New Speedway Boogie",
         "New Speedway Boogie Jam",
         "Next Time You See Me",
         "Next Time You See Me Jam",
         "Nobody's Fault",
         "Nobody's Fault Jam",
         "Oh Boy",
         "Okie From Muskogee",
         "Ollin Arrageed",
         "On The Road Again",
         "One Kind Favor",
         "Only A Fool",
         "Operator",
         "Other One",
         "Other One Jam",
         "Pain In My Heart",
         "Passenger",
         "Peggy Sue",
         "Peggy-O",
         "Phil & Ned",
         "Phil's Earthquake space",
         "Philo Stomp",
         "Picasso Moon",
         "Playin'",
         "Playin' Jam",
         "Playin' Reprise",
         "Pledging My Time",
         "Pollution",
         "Prisoner Blues",
         "Promised",
         "Proud Mary",
         "Pump Song",
         "Queen Jane Approximately",
         "Railroading The Great Divide",
         "Rain",
         "Rainy Day Women #12 And #35",
         "Ramble On",
         "Reuben And Cherise",
         "Revolution",
         "Revolutionary Hamstrung Blues",
         "Rider",
         "Riot In Cell Block #9",
         "Ripple",
         "Road Runner",
         "Roberta",
         "Rockin' Pneumonia & The Boogie Woogie Flu",
         "Roll In My Sweet Baby's Arms",
         "Rollin' And Tumblin'",
         "Rooster",
         "Rosalie McFall",
         "Rosemary",
         "Roses",
         "Row Jimmy",
         "Rubin And Cherise",
         "Run Rudolph Run",
         "Sage And Spirit",
         "Saint",
         "Salt Lake City",
         "Samba In The Rain",
         "Samson",
         "Sat. Night",
         "Satisfaction",
         "Sawmill",
         "Scarlet",
         "Searchin'",
         "Seasons",
         "Seasons Of My Heart",
         "Senor",
         "Shakedown",
         "She Belongs To Me",
         "She's Mine",
         "Shelter From The Storm",
         "Ship Of Fools",
         "Sick And Tired",
         "Sidewalks Of New York",
         "Silver Threads",
         "Silver Threads And Golden Needles",
         "Simple Twist Of Fate",
         "Sing Me Back Home",
         "Sitting On Top Of The World",
         "Slewfoot",
         "Slipknot!",
         "Slow Train",
         "Smokestack Lightnin'",
         "Smokestack Lightnin' Jam",
         "So Many Roads",
         "So Sad (To Watch Good Love Go Bad)",
         "So What",
         "So What Jam",
         "Something On Your Mind",
         "Space",
         "Space Jam",
         "Spanish Jam",
         "Spoonful",
         "St. Stephen Jam",
         "St.Stephen",
         "Stagger Lee",
         "Stander On The Mountain",
         "Standing On The Corner",
         "Standing On The Moon",
         "Star-Spangled Banner",
         "Stealin'",
         "Stella Blue",
         "Stir It Up",
         "Stranger",
         "Stronger Than Dirt",
         "Stuck Inside Of Mobile",
         "Sugar Magnolia",
         "Sugar Magnolia Jam",
         "Sugaree",
         "Sunrise",
         "Sunshine Daydream",
         "Supplication",
         "Supplocation Jam",
         "Swing Low Sweet Chariot",
         "TLEO",
         "Take It All Off",
         "Take Me To The River",
         "Takes A Train To Cry",
         "Tangled Up In Blue",
         "Tell It To Me",
         "Tell Mama",
         "Tennessee Jed",
         "Terrapin",
         "That Would Be Something",
         "That'll Be The Day",
         "That's All Right, Mama",
         "The Ballad Of Frankie Lee And Judas Priest",
         "The Boxer",
         "The Eleven",
         "The Eleven Jam",
         "The Flood",
         "The French Girl",
         "The Island",
         "The Race Is On",
         "The Raven Space",
         "The Rub",
         "The Rub Jam",
         "The Same Thing",
         "The Seven",
         "The Star Spangled Banner",
         "The Things I Used To Do",
         "The Times They Are A-Changin'",
         "The Weight",
         "The Wicked Messenger",
         "They Killed Him",
         "This Time Forever",
         "Throwing Stones",
         "Tiger By The Tail",
         "Till The Morning Comes",
         "To Lay Me Down",
         "Tom Dooley",
         "Tom Thumb's Blues",
         "Tomorrow Is A Long Time",
         "Tomorrow Is Forever",
         "Tomorrow Never Knows",
         "Tons Of Steel",
         "Touch Of Grey",
         "Truckin'",
         "Twist & Shout",
         "Two Soldiers Jam",
         "Two Souls In Communion",
         "Two Trains Running",
         "U.S. Blues",
         "Unbroken Chain",
         "Uncle",
         "Uncle John's",
         "Uncle John's Band Jam",
         "Under Your Spell",
         "Union Sundown",
         "Unknown Blues",
         "Unknown Jam",
         "Valley Road",
         "Victim",
         "Viola Lee Blues",
         "Visions Of Johanna",
         "WDWDIITR",
         "Wabash Cannonball",
         "Wake Up Little Susie",
         "Walk Down The Street",
         "Walkin The Dog",
         "Walkin' Blues",
         "Walkin' Down The Line",
         "Walking The Dog",
         "Wang Dand Doodle",
         "Warriors Of The Sun",
         "Watching The River Flow",
         "Watchtower",
         "Wave That FLag",
         "Wave To The Wind",
         "Way To Go Home",
         "We Can Run",
         "Weather Report Suite Part 1",
         "Weather Report Suite Prelude",
         "Werewolves",
         "West L.A. Fadeaway",
         "Wharf Rat",
         "What's Become Of The Baby",
         "What's Going On?",
         "Wheel",
         "When I Paint My Masterpiece",
         "When Push Comes To Shove",
         "Where Have All The Heroes Gone",
         "Who Do You Love",
         "Who's Lovin' You Tonight",
         "Willie And The Hand Jive",
         "Willie And The Hand JiveRosemary",
         "Winin' Boy Blues",
         "World To Give",
         "Wow Wow Hey Hey",
         "Yonder's Wall",
         "You Ain't Woman Enough",
         "You Don't Have To Ask",
         "You Don't Love Me",
         "You See A Broken Heart",
         "You Win Again",
         "You Won't Find Me",
         "Your Love At Home",
];

